version: '3.3'
services:
  influxdb:
    hostname: influxdb
    image: influxdb:1.8
    restart: always
    restart: always
    volumes:
      - ./influxdb:/var/lib/influxdb
  server:
    build: server
    hostname: server
    restart: always
    volumes:
      - ./server-scripts:/server-scripts
    ports:
      - 8888:8888
      - 8889:8889
    command: /server-scripts/start.sh
    restart: always
  grafana:
    image: grafana/grafana:latest
    hostname: grafana
    restart: always
    ports:
      - 3000:3000
volumes:
  mysql-data:
    driver: local

