version: '3.3'
services:
  influxdb:
    hostname: influxdb
    image: influxdb:1.8
    restart: always
    restart: always
    environment:
      - INFLUXDB_DB=tank
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    ports:
      - 8086:8086
    volumes:
      - ./influxdb:/var/lib/influxdb
  server:
    build: server
    hostname: server
    restart: always
    volumes:
      - ./scripts:/water_tank
    ports:
      - 8888:8888
      - 8889:8889
    command: /water_tank/start.sh
    restart: always
  grafana:
    image: grafana/grafana:latest
    hostname: grafana
    restart: always
    volumes:
      - ./grafana-data:/var/lib/grafana
    ports:
      - 3000:3000

