version: '3.8'
services:
  db:
    hostname:  db
    image: yobasystems/alpine-mariadb
    restart: always
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=tank
      - MYSQL_ROOT_PASSWORD=tank
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./mysql-scripts:/docker-entrypoint-initdb.d
  server:
    image: ubuntu
    hostname: server
    restart: always
    ports:
      - 8080:8080
      - 8081:8081
    command: tail -f /dev/null
    restart: always
  grafana:
    image: grafana/grafana-oss
    hostname: grafana
    restart: always
    ports:
      - 3000:3000
volumes:
  mysql-data:
    driver: local
